export const LIQ = [
  {
    id: 1,
    name: "Jack Daniels",
    image: "./assets/images/bottles/bottle1.avif",
    price: 40,
    //   discount: 12,
  },
  {
    id: 2,
    name: "Johny Walker",
    image: "./assets/images/bottles/bottle1.avif",
    price: 20,
    //   discount: 12,
  },
  {
    id: 3,
    name: "Ciroc",
    image: "./assets/images/bottles/bottle1.avif",
    price: 100,
    //   discount: 12,
  },
  {
    id: 4,
    name: "Chidoro",
    image: "./assets/images/bottles/bottle1.avif",
    price: 10,
    //   discount: 12,
  },
  {
    id: 5,
    name: "Qolder",
    image: "./assets/images/bottles/bottle1.avif",
    price: 200,
    //   discount: 12,
  },
  {
    id: 6,
    name: "Jack Daniels",
    image: "./assets/images/bottles/bottle1.avif",
    price: 40,
    //   discount: 12,
  },
  {
    id: 7,
    name: "Chidoro",
    image: "./assets/images/bottles/bottle1.avif",
    price: 10,
    //   discount: 12,
  },
];

export const NAD = [
  {
    id: 1,
    name: "Jack Daniels",
    image: "./assets/images/bottles/bottle1.avif",
    price: 40,
    //   discount: 12,
  },
  {
    id: 2,
    name: "Johny Walker",
    image: "./assets/images/bottles/bottle1.avif",
    price: 20,
    //   discount: 12,
  },
  {
    id: 3,
    name: "Ciroc",
    image: "./assets/images/bottles/bottle1.avif",
    price: 100,
    //   discount: 12,
  },
  {
    id: 4,
    name: "Chidoro",
    image: "./assets/images/bottles/bottle1.avif",
    price: 10,
    //   discount: 12,
  },
  {
    id: 5,
    name: "Qolder",
    image: "./assets/images/bottles/bottle1.avif",
    price: 200,
    //   discount: 12,
  },
  {
    id: 6,
    name: "Jack Daniels",
    image: "./assets/images/bottles/bottle1.avif",
    price: 40,
    //   discount: 12,
  },
  {
    id: 7,
    name: "Chidoro",
    image: "./assets/images/bottles/bottle1.avif",
    price: 10,
    //   discount: 12,
  },
];

export const WINE = [
  {
    id: 1,
    name: "Jack Daniels",
    image: "./assets/images/bottles/bottle1.avif",
    price: 40,
    //   discount: 12,
  },
  {
    id: 2,
    name: "Johny Walker",
    image: "./assets/images/bottles/bottle1.avif",
    price: 20,
    //   discount: 12,
  },
  {
    id: 3,
    name: "Ciroc",
    image: "./assets/images/bottles/bottle1.avif",
    price: 100,
    //   discount: 12,
  },
  {
    id: 4,
    name: "Chidoro",
    image: "./assets/images/bottles/bottle1.avif",
    price: 10,
    //   discount: 12,
  },
  {
    id: 5,
    name: "Qolder",
    image: "./assets/images/bottles/bottle1.avif",
    price: 200,
    //   discount: 12,
  },
  {
    id: 6,
    name: "Jack Daniels",
    image: "./assets/images/bottles/bottle1.avif",
    price: 40,
    //   discount: 12,
  },
  {
    id: 7,
    name: "Chidoro",
    image: "./assets/images/bottles/bottle1.avif",
    price: 10,
    //   discount: 12,
  },
];

export const BEER = [
  {
    id: 1,
    name: "Zambezi",
    image: "./assets/images/bottles/bottle1.avif",
    price: 40,
    //   discount: 12,
  },
  {
    id: 2,
    name: "Castle",
    image: "./assets/images/bottles/bottle1.avif",
    price: 20,
    //   discount: 12,
  },
  {
    id: 3,
    name: "Black Label",
    image: "./assets/images/bottles/bottle1.avif",
    price: 100,
    //   discount: 12,
  },
  {
    id: 4,
    name: "Heinken",
    image: "./assets/images/bottles/bottle1.avif",
    price: 10,
    //   discount: 12,
  },
  {
    id: 5,
    name: "Qolder",
    image: "./assets/images/bottles/bottle1.avif",
    price: 200,
    //   discount: 12,
  },
  {
    id: 6,
    name: "Jack Daniels",
    image: "./assets/images/bottles/bottle1.avif",
    price: 40,
    //   discount: 12,
  },
  {
    id: 7,
    name: "Chidoro",
    image: "./assets/images/bottles/bottle1.avif",
    price: 10,
    //   discount: 12,
  },
];
